export default {
  "1": {
    title: "Recycle Water Bottle",
    id: 1,
    points: 10,
    susAction: "waterBottle",
    image:
      "https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60",
    impact:
      "Plastic water bottles are becoming a growing segment of the municipal solid waste stream in the United States. The American Chemistry Council estimates that the average consumer uses 166 plastic water bottles each year and that 2.5 million plastic bottles are thrown away every hour. While plastic water bottles offer convenience, they also create unnecessary waste in landfills. By recycling your plastic water bottles, you can positively impact the environment in several ways.",
  },
  "2": {
    title: "Walk to the Village",
    id: 2,
    points: 30,
    susAction: "cmontWalk",
    image: "https://images.unsplash.com/photo-1529083660546-904a258c8a1c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60",
    impact: "Not only does walking improve the immediate effects by limiting pollution from car emissions, it can also contribute to the reduction of future expenditures. For example, over time, pollution causes damage to its surroundings, including both buildings and nature. By reducing the amount of carbon dioxide produced, less work and money will be needed to fix the impairment. Consequently, this money could go into other local requirements instead.",
  },
  "3": {
    title: "Bring Your Own Reusable Straw",
    id: 3,
    points: 15,
    susAction: "reuseStraw",
    image: "https://images.unsplash.com/photo-1586898993878-b33cd116520b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60",
    impact: "",
  },
  "4": {
    title: "Bring Reusable Bag",
    id: 4,
    points: 10,
    susAction: "reuseBag",
    image: "https://images.unsplash.com/photo-1567747450007-f324221e5598?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60",
    impact: "",
  },
  "5": {
    title: "Shop at the Farmers Market",
    id: 5,
    points: 35,
    susAction: "frmersMarket",
    image: "https://images.unsplash.com/photo-1444459094717-a39f1e3e0903?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60",
    impact: "",
  },
  "6": {
    title: "Re-brew Tea Leaves",
    id: 6,
    points: 10,
    susAction: "rebrewTea",
    image: "https://images.unsplash.com/photo-1519095615130-d36e0fe3bf63?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60",
    impact: "",
  },
  "7": {
    title: "No Food Waste from Meal",
    id: 7,
    points: 20,
    susAction: "noFoodWaste",
    image: "https://images.unsplash.com/photo-1529942376973-7dd96721339c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60",
    impact: "",
  },
  "8": {
    title: "Participate in Meatless-Mondays",
    id: 8,
    points: 20,
    susAction: "meatlessMon",
    image: "https://images.unsplash.com/photo-1556386470-bcdc6a5e9b9e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60",
    impact: "",
  },
  "9": {
    title: "Eco-friendly Cleaning Products",
    id: 9,
    points: 10,
    susAction: "ecoClean",
    image: "https://images.unsplash.com/photo-1583907659441-addbe699e921?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1000&q=60",
    impact: "",
  },
};
