export default {
  "1": {
    title: "Recycle Water Bottle",
    id: 1,
    points: 10,
    susAction: 'waterBottle',
    image: "",
    impact: "",
  },
  "2": {
    title: "Walk to the Village",
    id: 2,
    points: 30,
    susAction: 'cmontWalk',
    image: "",
    impact: "",
  },
  "3": {
    title: "Bring Your Own Reusable Straw",
    id: 3,
    points: 15,
    susAction: 'reuseStraw',
    image: "",
    impact: "",
  },
  "4": {
    title: "Bring Reusable Bag",
    id: 4,
    points: 10,
    susAction: 'reuseBag',
    image: "",
    impact: "",
  },
  "5": {
    title: "Shop at the Farmers Market",
    id: 5,
    points: 35,
    susAction: 'frmersMarket',
    image: "",
    impact: "",
  },
  "6": {
    title: "Re-brew Tea Leaves",
    id: 6,
    points: 10,
    susAction: 'rebrewTea',
    image: "",
    impact: "",
  },
  "7": {
    title: "No Food Waste from Meal",
    id: 7,
    points: 20,
    susAction: 'noFoodWaste',
    image: "",
    impact: "",
  },
  "8": {
    title: "Participate in Meatless-Mondays",
    id: 8,
    points: 20,
    susAction: 'meatlessMon',
    image: "",
    impact: "",
  },
  "9": {
    title: "Eco-friendly Cleaning Products",
    id: 9,
    points: 10,
    susAction: 'ecoClean',
    image: "",
    impact: "",
  },
};
